Feat/row class name
ant-design-blazor/ant-design-blazor pull request #1031
Opened 2021-01-22 20:37 UTC by mostrowski123

[[中文版模板 / Chinese template](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design-blazor/ant-design-blazor/issues/1025

### 💡 Background and solution

There currently is no way of conditionally applying styles to rows in a table. This is useful if you want to highlight a row  conditionally based on the row data. 
I fixed this by adding a `Func<RowData<TItem>, string> RowClassName` parameter to the table component and queried its value in the class attribute where rows are created.
<img width="1190" alt="Screen Shot 2021-01-22 at 3 28 18 PM" src="https://user-images.githubusercontent.com/5584495/105541886-7ae46300-5cc6-11eb-8672-75821bff7209.png">

### 📝 Changelog

I should note there is an issue when hovering on the highlighted rows as the hover color overrides the any color set by the custom style. I am not sure if this is acceptable or not, but I was unable to find a way to darken the color that is set. My apologies.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  add RowClassName attribute to table component  |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

2021-01-22 20:40 UTC, mostrowski123 commented
This is my first ever PR so my apologies for any mistakes or errors. I tried to follow the guidelines provided to the best of my ability.

2021-01-23 02:54 UTC, ElderJames commented
Thank you for you contribution @mostrowski123 

It's very nice.

2021-01-23 02:55 UTC, ElderJames requested changes

2021-01-23 02:55 UTC, ElderJames commented on components/table/Table.razor
> +                    <tr class="ant-table-expanded-row ant-table-expanded-row-level-1 @table.RowClassName(currentRowData)" style="@(currentRowData.Expanded?"":"display: none;")">
Here is an other peroperty for expand row.

![image](https://user-images.githubusercontent.com/7550366/105566892-7de45f80-5d69-11eb-9faf-cfdcf128fcf0.png)

2021-01-24 05:19 UTC, ElderJames approved these changes

2021-01-24 05:56 UTC, merged