Feat/table on row and cell
ant-design-blazor/ant-design-blazor pull request #1175
Opened 2021-02-25 12:54 UTC by qinhuaihe

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#1173 

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

2021-02-25 12:57 UTC, qinhuaihe commented
I have not finish the  `OnHeaderRow` and `OnHeaderCell` methods yet.

2021-02-25 12:59 UTC, qinhuaihe commented
I'm sorry for pushing the irrelevant old commits. I tried to fix it, but failed.

2021-02-25 13:06 UTC, qinhuaihe commented
Look at this [line](https://github.com/qinhuaihe/ant-design-blazor/blob/feat/table-on-row-and-cell/components/table/Column.razor.cs#L54). I can't use the ItemType as the generic parameter of RowData, so I have to cast the rowData when use it. Can I add another typeparam to Column?

```
Dictionary<string, object> OnCell(RowData rowData)
    {
        // have to cast rowData type
        var row = (RowData<Data>)rowData;

        Action<MouseEventArgs> OnClick = args =>
        {
            Console.WriteLine($"cell {row.Data.Name} was clicked");
        };

        return new Dictionary<string, object>()
        {
            { "onclick", OnClick },
        };
    }
```

2021-02-26 04:57 UTC, ElderJames requested changes

2021-02-26 04:57 UTC, ElderJames commented on site/AntDesign.Docs/Demos/Components/Table/demo/on-row-and-on-cell.md
> +������ `OnRow` `OnHeaderRow` `OnCell` `OnHeaderCell`��
please fix the encoding

2021-03-01 14:37 UTC, qinhuaihe commented
Please review the pr, we need this functionality urgently. Thank you in advance. 😀

2021-03-01 15:46 UTC, ElderJames approved these changes

2021-03-01 15:47 UTC, merged