feat(module: InputNumber): Add long click and keyboard event
ant-design-blazor/ant-design-blazor pull request #1235
Opened 2021-03-10 16:14 UTC by lingrepo

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

No such issue

### 💡 Background and solution

InputNumber‘s functions is not complete compared to offical AntDesign component.

### 📝 Changelog

1. When hold mouse down will always trigger the increase or decrease
2. `ArrowUp` or `ArrowDown` key can increase or decrease value

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

2021-03-10 16:20 UTC, ElderJames requested changes

2021-03-10 16:20 UTC, ElderJames commented on components/input-number/InputNumber.razor.cs
> +        private int? _decimalPlaces;
The fields should be placed below the properties.

2021-03-10 16:54 UTC, lingrepo commented on components/input-number/InputNumber.razor.cs
> +        private int? _decimalPlaces;
CodeMaid插件的问题，已修改

2021-03-11 04:59 UTC, ElderJames approved these changes

2021-03-11 05:23 UTC, merged