fix: some components are incorrect in RTL mode
ant-design-blazor/ant-design-blazor pull request #1300
Opened 2021-04-02 08:28 UTC by mutouzdl

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

RTL模式对于dropdown类型组件的最大改动有两个：
1. 组件多了一个{PrefixCls}-rtl样式类，如：ant-picker-dropdown-rtl
2. Placement由BottomLeft 改为 BottomRight
--------------------------------------------
There are two major changes that RTL mode makes to a dropdown-type component:
1. There is a {Prefixcls} -RTL css for components, e.g. ant-picker-dropdown-rtl
2. Placement is changed from BottomLeft to BottomRight

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

2021-04-02 10:39 UTC, ElderJames requested changes

2021-04-02 10:39 UTC, ElderJames commented on components/core/Component/overlay/OverlayTrigger.razor.cs
> +            if (RTL)
It should be restored when switching back to the LTR.

2021-04-02 16:03 UTC, ElderJames commented
![image](https://user-images.githubusercontent.com/7550366/113432443-f58cd580-940f-11eb-9730-e9fcd9b2b12a.png)

2021-04-06 10:10 UTC, mutouzdl commented
@ElderJames I have fixed the two problems you mentioned above

2021-04-06 11:04 UTC, ElderJames approved these changes

2021-04-06 12:02 UTC, merged