fix(module: affix): affix to the viewport (#1327)
ant-design-blazor/ant-design-blazor pull request #1335
Opened 2021-04-11 03:27 UTC by skystardust

* fix target to element

2021-04-11 03:27 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1335) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1335) before we can accept your contribution.<br/><br/>:x: skystardust [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1335)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1335) it.</sub>

2021-04-11 03:45 UTC, ElderJames commented
Thanks for contribution. Please sign the CLA first.

2021-04-11 07:38 UTC, ElderJames requested changes

2021-04-11 07:38 UTC, ElderJames commented on components/affix/Affix.razor.cs
> +        public string TargetId { get; set; }
Please use css selecter, don't only use id.

2021-04-14 05:40 UTC, ElderJames commented
Hi @skystardust , please sign the CLA.

2021-04-14 15:20 UTC, merged