modify status unsuccessfully after initialization & add change result demo
ant-design-blazor/ant-design-blazor pull request #1336
Opened 2021-04-11 05:14 UTC by JiaChengLuo

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#1328 

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

2021-04-11 05:14 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1336) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1336) before we can accept your contribution.<br/><br/>:x: JiaChengLuo [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1336)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1336) it.</sub>

2021-04-11 07:34 UTC, ElderJames requested changes

2021-04-11 07:34 UTC, ElderJames commented on site/AntDesign.Docs/Demos/Components/Result/demo/changeTheResult.md
> +```
please delete these lines

2021-04-12 10:21 UTC, ElderJames approved these changes

2021-04-12 10:22 UTC, merged