Update Drawer.razor.cs 修改宽度可自适应
ant-design-blazor/ant-design-blazor pull request #1390
Opened 2021-04-20 03:09 UTC by Nrtyck

2021-04-20 03:09 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1390) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1390) before we can accept your contribution.<br/><br/>:x: Nrtyck [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1390)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1390) it.</sub>

2021-04-20 03:25 UTC, ElderJames requested changes

2021-04-20 03:25 UTC, ElderJames commented on components/drawer/Drawer.razor.cs
>          [Parameter] public int Height { get; set; } = 256;
`Height` also need to be string.

2021-04-20 03:25 UTC, ElderJames commented
Thanks for contribution @Nrtyck 
Please sign the CLA, and fix the build errors.

2021-04-21 02:03 UTC, ElderJames requested changes

2021-04-21 02:03 UTC, ElderJames commented on site/AntDesign.Docs/Demos/Components/Drawer/demo/Multiple.razor
> +           int w = int.Parse(wdFirstLayer) + 260;
Please use `TryParse`

2021-04-21 02:03 UTC, ElderJames commented on site/AntDesign.Docs/Demos/Components/Drawer/demo/Multiple.razor
> +           int w = int.Parse(wdFirstLayer);
Please use `TryParse`

2021-04-21 10:11 UTC, zxyao145 commented
Hi, @Nrtyck 
Please add the description for this PR.

2021-04-24 03:23 UTC, Nrtyck commented
Drawer change  width and  height  vw vh

2021-04-24 03:42 UTC, closed without merging