Replaced IdGeneratorHelper with DI service that can be replaced by user
ant-design-blazor/ant-design-blazor pull request #664
Opened 2020-10-04 11:48 UTC by shutdown256

[[中文版模板 / Chinese template](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

### 💡 Background and solution

* Currently all `AntDomComponentBase` implementations set their ids to randomly generated guid with ant-blazor- prefix this may not be desirable for all users and also not very performant.
* Removed `IdGeneratorHelper` and replaced it with injected service implementing `IComponentIdGenerator`
* Possible custom version could look like this:
```c#
public class AndDesignIdGenerator : IComponentIdGenerator {
    private int nextId = 0;
    public string Generate(AntDomComponentBase component) => "ant-blazor-" + Interlocked.Increment(ref nextId);
}
```

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Users can inject custom implementation of `IComponentIdGenerator` in order to change it's default behaviour to their liking.      |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

2020-10-04 17:35 UTC, ElderJames requested changes

2020-10-04 17:35 UTC, ElderJames commented on components/core/Base/AntDomComponentBase.cs
> +            Id = ComponentIdGenerator.Generate(this);
Please check the `Id` is null before assigning a auto-generated value.

2020-10-04 17:36 UTC, ElderJames commented
Thanks for contribution @shutdown256 !

2020-10-04 19:22 UTC, shutdown256 commented on components/core/Base/AntDomComponentBase.cs
> +            Id = ComponentIdGenerator.Generate(this);
done

2020-10-10 07:30 UTC, ElderJames approved these changes

2020-10-10 07:31 UTC, merged