fix: using ConfimRef to close Confirm dialog but not reset body's scroll bar (#883)
ant-design-blazor/ant-design-blazor pull request #884
Opened 2020-12-13 08:33 UTC by zxyao145

[[中文版模板 / Chinese template](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#883 

### 💡 Background and solution

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix: using ConfimRef to close Confirm dialog but not reset body's scroll bar  |
| 🇨🇳 Chinese | 修复使用 ConfimRef  关闭 Confirm 对话框时无法重置 body 滚动条的问题  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

2020-12-13 08:49 UTC, ElderJames approved these changes

2020-12-13 08:52 UTC, ElderJames requested changes

2020-12-13 08:52 UTC, ElderJames commented on components/modal/ComfirmContainer.razor.cs
> +                await JsInvokeAsync(JSInteropConstants.EnableBodyScroll);
如果弹出了多个modal，这里是不是要先判断 modalRefs 已经是空了再掉出滚动？

2020-12-14 15:19 UTC, zxyao145 commented on components/modal/ComfirmContainer.razor.cs
> +                await JsInvokeAsync(JSInteropConstants.EnableBodyScroll);
modalRefs 如果为空了，_modalRefs.Contains(confirmRef) 就会返回 false 呀。
JSInteropConstants.EnableBodyScroll 是基于栈的，每次关闭 Dialog 都应该执行此函数的。

2020-12-24 05:58 UTC, ElderJames approved these changes

2020-12-24 06:00 UTC, merged